export const coachTableBodyStub = [
  {
    name: "John",
    age: "28",
    designation: "Head Coach",
    sportCoaching: "Basketball, Tennis",
    gender: "M",
    batches: "2",
    contactNo: "+41234567890",
  },
  {
    name: "John",
    age: "28",
    designation: "Head Coach",
    sportCoaching: "Basketball, Tennis",
    gender: "M",
    batches: "2",
    contactNo: "+41234567890",
  },
  {
    name: "John",
    age: "28",
    designation: "Head Coach",
    sportCoaching: "Basketball, Tennis",
    gender: "M",
    batches: "2",
    contactNo: "+41234567890",
  },
  {
    name: "John",
    age: "28",
    designation: "Head Coach",
    sportCoaching: "Basketball, Tennis",
    gender: "M",
    batches: "2",
    contactNo: "+41234567890",
  },
  {
    name: "John",
    age: "28",
    designation: "Head Coach",
    sportCoaching: "Basketball, Tennis",
    gender: "M",
    batches: "2",
    contactNo: "+41234567890",
  },
  {
    name: "John",
    age: "28",
    designation: "Head Coach",
    sportCoaching: "Basketball, Tennis",
    gender: "M",
    batches: "2",
    contactNo: "+41234567890",
  },
  {
    name: "John",
    age: "28",
    designation: "Head Coach",
    sportCoaching: "Basketball, Tennis",
    gender: "M",
    batches: "2",
    contactNo: "+41234567890",
  },
  {
    name: "John",
    age: "28",
    designation: "Head Coach",
    sportCoaching: "Basketball, Tennis",
    gender: "M",
    batches: "2",
    contactNo: "+41234567890",
  },
  {
    name: "John",
    age: "28",
    designation: "Head Coach",
    sportCoaching: "Basketball, Tennis",
    gender: "M",
    batches: "2",
    contactNo: "+41234567890",
  },
];
